FROM php:8.1-cli

# Create app folder
WORKDIR /app

# Copy everything
COPY . .

# Create a new user and give permissions
RUN adduser --disabled-password --gecos '' appuser && \
    mkdir -p /app/cache && \
    chown -R appuser:appuser /app

# Switch to new user
USER appuser

# Start PHP server
CMD ["php", "-S", "0.0.0.0:8080"]
